ElectroDocument/Controllers/DocsController.cs
using ElectroDocument.Controllers.AppContext;
using ElectroDocument.Controllers.Services;
using ElectroDocument.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Spire.Doc;
using System.Reflection.Metadata;
using System.Security.Claims;
using DocumentFormat.OpenXml.Packaging;
using OpenXmlPowerTools;
using System.IO.Packaging;
using System.Xml.Linq;
using Document = Spire.Doc.Document;
using System.Text;
using System.IO;
using System.Xml.Serialization;

namespace ElectroDocument.Controllers
{
    [Authorize]
    public class DocsController : Controller
    {
        DocsService service;
        UserService userService;
        RoleService roleService;

        public DocsController(DocsService service, UserService userService, RoleService roleService)
        {
            this.service = service;
            this.userService = userService;
            this.roleService=roleService;
        }

        [Authorize(Policy = "AdminOrUser")]
        public async Task<IActionResult> Index(long? id)
        {

            DocsModel model;
            model = new DocsModel();
            if (id is not null)
            {
                model.docs = service.GetFullDocsByUserId(id.Value);
            }
            else
            {
                IEnumerable<Claim> claims = User.Claims;
                Claim claim = claims.Where(claim => claim.Type == ClaimTypes.NameIdentifier).First();
                string dbid = claim.Value;
                Employee? emp = await userService.GetEmployeeAsync(dbid);
                model.docs = service.GetFullDocsByUserIdNotifyExt(emp.Id);
            }
            return View(model);
        }


        public async Task<IActionResult> View(long? id)
        {
            var model = new
            {
                Id = id.Value
            };
            return base.View(model);
        }


        [HttpGet]
        public async Task<FileContentResult> GenerateDocument(string id)
        {
            Document doc = await service.GenerateDocument(Convert.ToInt64(id));

            using (MemoryStream stream = new MemoryStream())
            {
                doc.SaveToStream(stream, FileFormat.Docx);

                // Do something with the MemoryStream if needed
                // For example, you can convert it to a byte array
                byte[] byteArray = stream.ToArray();
                var contentType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
                // Now you can use the byteArray for further processing
                return File(byteArray, contentType);
            }
        }

        [HttpGet]
        public async Task<FileContentResult> GenerateDocumentPDF(string id)
        {

            Document doc = await service.GenerateDocument(Convert.ToInt64(id));
            
            using (MemoryStream docxStream = new MemoryStream())
            {
                try
                {
                    doc.SaveToStream(docxStream, FileFormat.Docx);
                    var source = Package.Open(docxStream);
                    var document = WordprocessingDocument.Open(source);
                    HtmlConverterSettings settings = new HtmlConverterSettings();
                    XElement html = HtmlConverter.ConvertToHtml(document, settings);
                    byte[] result = Encoding.UTF8.GetBytes(html.ToString());
                    var contentType = "text/html;charset=utf-8";
                    return File(result, contentType);
                }
                catch 
                {
                    doc.SaveToStream(docxStream, FileFormat.PDF);
                    byte[] byteArray = docxStream.ToArray();
                    var contentType = "application/pdf";
                    return File(byteArray, contentType);
                }

            }
        }

        [Authorize(Policy = "Editing")]
        [HttpGet]
        public async Task<ActionResult> EmployeeContract(string? id, string? edit)
        {
            Employee emp = await userService.GetEmployeeAsync(id);

            EmployeeContractModel model = new EmployeeContractModel();
            model.Fullname = $"{emp.Individual.Name} {emp.Individual.Surname} {emp.Individual.Patronymic}";
            model.id = Convert.ToInt64(id);
            model.Roles = await roleService.GetRolesAsync();

            if (edit is not null)
            {
                model.DocId = Convert.ToInt64(edit);
            }

            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> EditDoc(string id)
        {
            Doc targetDoc = service.GetDocById(Convert.ToInt64(id));
            switch (targetDoc.DocType)
            {
                case (sbyte?)DocumentTypes.Moved: return Redirect($"/Docs/Moved?id={targetDoc.EmployeeId}&Edit={id}");
                case (sbyte?)DocumentTypes.Weekend: return Redirect($"/Docs/Weekend?id={targetDoc.EmployeeId}&Edit={id}");
                case (sbyte?)DocumentTypes.Dismissed: return Redirect($"/Docs/Dismissed?id={targetDoc.EmployeeId}&Edit={id}");
                case (sbyte?)DocumentTypes.EmploymentContract: return Redirect($"/Docs/EmployeeContract?id={targetDoc.EmployeeId}&Edit={id}");
                case (sbyte?)DocumentTypes.Encouragement: return Redirect($"/Docs/Encourage?id={targetDoc.EmployeeId}&Edit={id}");
                case (sbyte?)DocumentTypes.Deprivation: return Redirect($"/Docs/Deprivation?id={targetDoc.EmployeeId}&Edit={id}");
            }

            return Redirect("/Home");
        }


        [Authorize(Policy = "Editing")]
        [HttpGet]
        public async Task<ActionResult> Moved(string? id, string? edit)
        {
            Employee emp = await userService.GetEmployeeAsync(id);

            EmployeeContractModel model = new EmployeeContractModel();
            model.Fullname = $"{emp.Individual.Name} {emp.Individual.Surname} {emp.Individual.Patronymic}";
            model.id = Convert.ToInt64(id);
            model.Roles = await roleService.GetRolesAsync();

            if (edit is not null)
            {
                model.DocId = Convert.ToInt64(edit);
            }

            return View(model);
        }

        [Authorize(Policy = "Editing")]
        [HttpGet]
        public async Task<ActionResult> Dismissed(string? id, string? edit)
        {
            Employee emp = await userService.GetEmployeeAsync(id);

            EmployeeContractModel model = new EmployeeContractModel();
            model.Fullname = $"{emp.Individual.Name} {emp.Individual.Surname} {emp.Individual.Patronymic}";
            model.id = Convert.ToInt64(id);
            model.Roles = await roleService.GetRolesAsync();

            if (edit is not null)
            {
                model.DocId = Convert.ToInt64(edit);
            }

            return View(model);
        }

        [Authorize(Policy = "Editing")]
        [HttpGet]
        public async Task<ActionResult> Weekend(string? id, string? edit)
        {
            Employee emp = await userService.GetEmployeeAsync(id);

            EmployeeContractModel model = new EmployeeContractModel();
            model.Fullname = $"{emp.Individual.Name} {emp.Individual.Surname} {emp.Individual.Patronymic}";
            model.id = Convert.ToInt64(id);
            model.Roles = await roleService.GetRolesAsync();

            if (edit is not null)
            {
                model.DocId = Convert.ToInt64(edit);
            }

            return View(model);
        }

        [Authorize(Policy = "Admin")]
        public async Task<ActionResult> RoleCreate(string? id, string? edit)
        {
            Employee emp = await userService.GetEmployeeAsync(id);

            EmployeeContractModel model = new EmployeeContractModel();
            model.Fullname = $"{emp.Individual.Name} {emp.Individual.Surname} {emp.Individual.Patronymic}";
            model.id = Convert.ToInt64(id);
            model.Roles = await roleService.GetRolesAsync();


            if (edit is not null)
            {
                model.DocId = Convert.ToInt64(edit);
            }

            return View(model);
        }

        [Authorize(Policy = "Editing")]
        public async Task<ActionResult> Encourage(string? id, string? edit)
        {
            Employee emp = await userService.GetEmployeeAsync(id);

            EmployeeContractModel model = new EmployeeContractModel();
            model.Fullname = $"{emp.Individual.Name} {emp.Individual.Surname} {emp.Individual.Patronymic}";
            model.id = Convert.ToInt64(id);
            model.Roles = await roleService.GetRolesAsync();


            if (edit is not null)
            {
                model.DocId = Convert.ToInt64(edit);
            }

            return View(model);
        }

        [Authorize(Policy = "Editing")]
        public async Task<ActionResult> Deprivation(string? id, string? edit)
        {
            Employee emp = await userService.GetEmployeeAsync(id);

            EmployeeContractModel model = new EmployeeContractModel();
            model.Fullname = $"{emp.Individual.Name} {emp.Individual.Surname} {emp.Individual.Patronymic}";
            model.id = Convert.ToInt64(id);
            model.Roles = await roleService.GetRolesAsync();

            if (edit is not null)
            {
                model.DocId = Convert.ToInt64(edit);
            }

            return View(model);
        }

        [Authorize(Policy = "Editing")]
        [HttpPost]
        public async Task<IResult> GenerateEmployeeContract([FromForm] GenerateEmployeeContractModel model)
        {
            Employee emp = await userService.GetEmployeeAsync(model.id.ToString());


ElectroDocument/Controllers/NotificationController.cs
using ElectroDocument.Controllers.AppContext;
using ElectroDocument.Controllers.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.IdentityModel.Abstractions;
using System.Security.Claims;

namespace ElectroDocument.Controllers
{
    public record DefaultNotificationRequest(long EmpId);
    public record NotificationUpdateStatusRequest(long EmpId, long DocId);

    [Authorize(Policy = "AdminOrUser")]
    public class NotificationController : Controller
    {
        private NotificationService notificationService;
        private DocsService documentService;

        public NotificationController(NotificationService notificationService, DocsService documentService)
        {
            this.notificationService = notificationService;
            this.documentService = documentService;

        }

        public async Task<ActionResult> Index()
        {
            var userClaims = User.Claims;
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var docsCount = await notificationService.GetNotificationCount(Convert.ToInt64(userId));

            if (docsCount <= 0)
            {
                return RedirectToAction("Index", "Home");
            }

            var model = new
            {
                docs = await notificationService.GetUnseenDocuments(Convert.ToInt64(userId))
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IResult> GetNotificationCount([FromBody] DefaultNotificationRequest req)
        {
            int count = await notificationService.GetNotificationCount(req.EmpId);

            var response = new
            {
                count = count
            };

            return Results.Json(response);
        }

        [HttpPost]
        public async Task<IResult> AcceptAllNotifications([FromBody] DefaultNotificationRequest req)
        {
            await notificationService.NotifiedAll(req.EmpId);
            return Results.Ok(null);
        }


        [HttpPost]
        public async Task<IEnumerable<Doc>> GetUnseenDocs([FromBody] DefaultNotificationRequest req)
        {
            return await notificationService.GetUnseenDocuments(req.EmpId);
        }

        [HttpPost]
        public async Task<IResult> SetNotification([FromBody] NotificationUpdateStatusRequest req)
        {
            return Results.Ok(await notificationService.Notified(req.EmpId, req.DocId));
        }

    }
}

ElectroDocument/Controllers/RoleController.cs
using ElectroDocument.Controllers.AppContext;
using ElectroDocument.Controllers.Services;
using ElectroDocument.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Security.Claims;

namespace ElectroDocument.Controllers
{
	[Authorize(Policy = "Editing")]
	public class RoleController : Controller
	{
		private RoleService roleService;

		public RoleController(RoleService roleService) 
		{
			this.roleService = roleService;
		}

        [Authorize(Policy = "Editing")]
        public async Task<IActionResult> Index()
		{
            //List<RoleModelTableRow> rows = new List<RoleModelTableRow>();

            //foreach(Role r in await roleService.GetRolesAsync())
            //{
            //	rows.Add(new RoleModelTableRow { Id = r.Id, AccessLevel = r.AccessLevel, Name = r.Title, EmployeeCount = r.Employees.Count });

            //         }

            return View(new RoleModel { rolesTable = await roleService.GetRolesAsync()});
		}

        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Create()
		{
            IEnumerable<Claim> claims = User.Claims;
            Claim claim = claims.Where(claim => claim.Type == ClaimTypes.NameIdentifier).First();
            string id = claim.Value;

			var model = new
			{
				Id = Convert.ToInt64(id),
			};

            return View(model);
		}

        [Authorize(Policy = "Admin")]
        public async Task<IResult> Add([FromBody] RoleCreateModel model)
		{
			roleService.CreateRole(model);

			return Results.Ok(model);
        }
	}
}

ElectroDocument/Views/Shared/_Layout.cshtml
@using ElectroDocument.Controllers.AppContext
@using Microsoft.AspNetCore.Authorization
@using System.Security.Claims
@using Microsoft.AspNetCore.Identity
@using ElectroDocument.Controllers.Services;

@inject NotificationService NotificationService;
@inject UserService userService;
@inject IAuthorizationService AuthorizationService;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ElectroDocument</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ElectroDocument.styles.css" asp-append-version="true" />
    <style>
        .nav-item-photo
        {
            max-width: 98px;
            max-height: 98px;
            border-radius: 40%;
        }

        .nav-item-exit
        {
            padding-top: 10px;
        }
        .nav-link-exit
        {
            max-width: 28px;
            max-height: 28px;
            border-radius: 80%;

        }

        .nav-link-exit:hover {
            background: gray;
        }

        .nav-link-notify
        {
            max-width: 28px;
            max-height: 28px;
            border-radius: 50%;
        }


        .notification {
            background-color: white;
            color: white;
            text-decoration: none;
            padding: 2px 2px;
            position: relative;
            display: inline-block;
            border-radius: 50%;
        }

            .notification:hover {
                background: gray;
            }

            .notification .badge {
                position: absolute;
                top: -10px;
                right: -10px;
                padding: 5px 10px;
                border-radius: 50%;
                background-color: blue;
                color: white;
                display: none;
            }?

    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ElectroDocument</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная страница</a>
                        </li>
                        @if (@Context.User.Identity.IsAuthenticated)
                        {
                            var res = await AuthorizationService.AuthorizeAsync(User, "Editing");
                            @if (res.Succeeded)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Пользователи</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Должности</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Docs" asp-action="Index">Мои документы</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="Index">Профиль</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Index">Авторизация</a>
                            </li>
                        }
@*                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Приватность</a>
                        </li> *@
                        <li class="nav-item">
                            <hr class="dropdown-divider">
                        </li>
                    </ul>
                    @if (@Context.User.Identity.IsAuthenticated)
                    {
                        var userClaims = User.Claims;
                        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                        Employee? emp = await userService.GetEmployeeAsync(userId);
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <span class="nav-link text-dark">@emp.Individual.Name @emp.Individual.Surname</span> <!-- ФИО пользователя -->
                            </li>

                            <li class="nav-item">
                                <img src="/Profile/Image/@userId" alt="User Photo" class="nav-item-photo"> <!-- Фотография пользователя -->
                            </li>
                            <li class="nav-item">
                                <div class="notification">
                                    <span id="notCount" class="badge">0</span>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Notification" asp-action="Index">
                                        <img src="https://www.svgrepo.com/download/31480/notification-bell.svg" alt="Notification" class="nav-link-notify nav-item-photo text-dark"> <!-- Уведомления -->
                                    </a>
                                </div>
                            </li>
                            <li class="nav-item nav-item-exit">
                                <img src="https://www.svgrepo.com/download/42231/exit.svg" alt="Exit" class="nav-link-exit nav-item-photo text-dark"> <!-- Кнопка выхода -->
                            </li>

                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ElectroDocument @* - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
        </div>
    </footer>
    @if (@Context.User.Identity.IsAuthenticated)
    {
        var userClaims = User.Claims;
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        <script>

            async function UpdateNotificationCount() {
                bubble = document.getElementById('notCount');

                try {
                    let response = await fetch("/Notification/GetNotificationCount", {
                        method: "POST",
                        headers: { "Accept": "application/json", "Content-Type": "application/json" },
                        body: JSON.stringify({
                            empId: @userId
                        })
                    });


                    if (response.ok) {
                        let res = await response.json();
                        if (res.count != 0) {
                            bubble.innerHTML = res.count;
                            bubble.style.display = "block";
                        }
                        else {
                        }


                    } else {
                        console.error('Failed to fetch notification count:', response.status);
                    }
                } catch (error) {
                    console.error('Error fetching notification count:', error);
                }
            }

            window.addEventListener("load", async (event) => {
                await UpdateNotificationCount();
                setInterval(UpdateNotificationCount, 10000);
            });
        </script>
    }

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>